name: 'gregan'
version: '1.0.0'
config-version: 2

profile: 'gregan'

model-paths: ["models"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
clean-targets: ["target", "dbt_packages"]

models:
  gregan:
    staging:
      +materialized: view
    marts:
      +materialized: table
